name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres: 
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      SQLX_VERSION: 0.5.5
      SQLX_FEATURES: postgres
    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo Dependencies
      id: cache-build 
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}


    - name: Cache sqlx-cli
      uses: actions/cache@v3
      id: cache-sqlx
      with:
        path: |
          ~/.cargo/bin/sqlx

    - name: Install sqlx-cli
      uses: actions-rs/cargo@v1
      if: steps.cache-sqlx.outputs.cache-hit == false
      with:
        command: install
        args: >
            sqlx-cli
            --force
            --version=${{ env.SQLX_VERSION}}
            --features=${{ env.SQLX_FEATURES}}
            --no-default-features
            --locked

    - name: Migrate database
      run: |
        sudo apt-get install libpq-dev -y
        SKIP_DOCKER=true ./scripts/init_db.sh

    - name: Test
      run: cargo test --verbose
